"use client";
import React, { useState } from 'react';
import { usePlayerStore } from '@/store/usePlayerStore';
import { RPGItem } from '@/types/game';

export default function InventoryPage() {
  const inventory = usePlayerStore((state) => state.inventory);
  const [selectedItem, setSelectedItem] = useState<RPGItem | null>(inventory[0] || null);

  const getRarityClass = (rarity: string) => {
    switch (rarity) {
      case 'legendary': return 'border-yellow-400 bg-yellow-950/40 text-yellow-300';
      case 'epic': return 'border-purple-400 bg-purple-950/40 text-purple-300';
      case 'rare': return 'border-blue-400 bg-blue-950/40 text-blue-300';
      default: return 'border-gray-400 bg-gray-900 text-gray-300';
    }
  };

  const getRarityText = (rarity: string) => {
    switch (rarity) {
      case 'legendary': return 'LEGENDARY';
      case 'epic': return 'EPIC';
      case 'rare': return 'RARE';
      default: return 'COMMON';
    }
  };

  return (
    <div className="space-y-6 pt-4 animate-fade-in">
      <div className="flex justify-between items-center border-b-4 border-white pb-4">
        <h1 className="text-base md:text-xl font-bold text-[#f4a261]">
          [MY REWARD ITEMS] ({inventory.length})
        </h1>
        <span className="text-xs text-gray-400">AI-generated pixel rewards earned from your verified photo check-ins</span>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
        {/* Left Inventory Grid */}
        <div className="md:col-span-2 nes-container is-dark p-4 bg-[#121212]">
          {inventory.length === 0 ? (
            <div className="text-center py-16 text-gray-500 text-xs">
              No items yet. Complete a task check-in with a photo proof to earn pixel items!
            </div>
          ) : (
            <div className="grid grid-cols-2 sm:grid-cols-3 md:grid-cols-4 gap-4">
              {inventory.map((item) => {
                const isSelected = selectedItem?.id === item.id;
                return (
                  <div
                    key={item.id}
                    onClick={() => setSelectedItem(item)}
                    className={`border-4 p-3 bg-black cursor-pointer transition-all hover:scale-105 flex flex-col items-center justify-between text-center min-h-[140px] ${isSelected ? 'border-[#e76f51] shadow-[0_0_15px_#e76f51]' : 'border-gray-700'}`}
                  >
                    <div className="w-16 h-16 bg-[#1a1a1a] flex items-center justify-center border border-gray-800 p-1 mb-2 overflow-hidden">
                      <img src={item.image_base64} alt={item.name} className="w-full h-full object-contain image-pixelated" />
                    </div>
                    <p className="text-[10px] font-bold text-white truncate w-full">{item.name}</p>
                    <span className="text-[9px] text-gray-500 mt-1">[{item.real_world_object}]</span>
                  </div>
                );
              })}
            </div>
          )}
        </div>

        {/* Right Inspector */}
        <div className="nes-container is-dark with-title p-6 bg-[#121212] flex flex-col justify-between">
          <p className="title text-xs text-[#f4a261]">[ITEM DETAILS]</p>
          
          {selectedItem ? (
            <div className="space-y-4 text-xs">
              <div className="w-32 h-32 mx-auto bg-black border-4 border-white p-2 flex items-center justify-center shadow-inner">
                <img src={selectedItem.image_base64} alt={selectedItem.name} className="w-full h-full object-contain image-pixelated" />
              </div>

              <div className="text-center">
                <h2 className="text-sm font-bold text-[#f4a261] mb-1">{selectedItem.name}</h2>
                <span className={`inline-block px-2 py-1 text-[10px] border mb-3 ${getRarityClass(selectedItem.rarity)}`}>
                  {getRarityText(selectedItem.rarity)}
                </span>
              </div>

              <div className="space-y-2 border-t border-gray-800 pt-3">
                <p className="text-gray-400">Detected Object: <span className="text-white">{selectedItem.real_world_object}</span></p>
                <p className="text-gray-400">Description:</p>
                <p className="text-white leading-relaxed bg-black/60 p-3 border border-gray-800 font-mono text-[11px]">
                  {selectedItem.lore}
                </p>
              </div>
            </div>
          ) : (
            <div className="text-center py-20 text-gray-600 text-xs">
              Select an item on the left...
            </div>
          )}

          <div className="border-t border-gray-800 pt-4 mt-6 text-center text-[10px] text-gray-500">
            * Generated by AI background removal &amp; 16-color pixel engine
          </div>
        </div>
      </div>
    </div>
  );
}
